def get_config():
    dic_agent_conf = {
        'CNN_layers': [[32, 32]],
        'att_regularization': False,
        'rularization_rate': 0.03,
        'LEARNING_RATE': 0.0005,
        'SAMPLE_SIZE': 1000,
        'BATCH_SIZE': 32,
        'EPOCHS': 100,
        'UPDATE_Q_BAR_FREQ': 5,
        'UPDATE_Q_BAR_EVERY_C_ROUND': False,
        'GAMMA': 0.8,
        'MAX_MEMORY_LEN': 10000,
        'PATIENCE': 10,
        'D_DENSE': 20,
        'N_LAYER': 2,
        'EPSILON': 0.8,
        'EPSILON_DECAY': 0.95,
        'MIN_EPSILON': 0.2,
        'LOSS_FUNCTION': 'mean_squared_error',
        'SEPARATE_MEMORY': False,
        'NORMAL_FACTOR': 20,
        'TRAFFIC_FILE': 'anon_4_4_hangzhou_real_5816.json'
    }

    dic_exp_conf = {
        'RUN_COUNTS': 3600,
        'TRAFFIC_FILE': ['anon_4_4_hangzhou_real_5816.json'],
        'MODEL_NAME': 'CoLight',
        'NUM_ROUNDS': 100,
        'NUM_GENERATORS': 4,
        'LIST_MODEL': ['Fixedtime', 'SOTL', 'Deeplight', 'SimpleDQN'],
        'LIST_MODEL_NEED_TO_UPDATE': ['Deeplight', 'SimpleDQN', 'CoLight', 'GCN', 'SimpleDQNOne', 'Lit'],
        'MODEL_POOL': False,
        'NUM_BEST_MODEL': 3,
        'PRETRAIN': False,
        'PRETRAIN_MODEL_NAME': 'CoLight',
        'PRETRAIN_NUM_ROUNDS': 0,
        'PRETRAIN_NUM_GENERATORS': 15,
        'AGGREGATE': False,
        'DEBUG': False,
        'EARLY_STOP': False,
        'MULTI_TRAFFIC': False,
        'MULTI_RANDOM': False,
        'ROADNET_FILE': 'roadnet_single.json'
    }

    dic_traffic_env_conf = {
        'max_lane_num': [40,40,40,40,40,40,40,40,40,40,40,40],
        'ACTION_PATTERN': 'set',
        'NUM_INTERSECTIONS': 1,
        'MIN_ACTION_TIME': 10,
        'YELLOW_TIME': 5,
        'ALL_RED_TIME': 0,
        'NUM_PHASES': 2,
        'NUM_LANES': 1,
        'ACTION_DIM': 2,
        'MEASURE_TIME': 10,
        'IF_GUI': False,
        'DEBUG': False,
        'INTERVAL': 1,
        'THREADNUM': 8,
        'SAVEREPLAY': False,
        'RLTRAFFICLIGHT': True,
        'DIC_FEATURE_DIM': {
            'D_LANE_QUEUE_LENGTH': (4,),
            'D_LANE_NUM_VEHICLE': (4,),
            'D_COMING_VEHICLE': (12,),
            'D_LEAVING_VEHICLE': (12,),
            'D_LANE_NUM_VEHICLE_BEEN_STOPPED_THRES1': (4,),
            'D_CUR_PHASE': (8,),
            'D_NEXT_PHASE': (1,),
            'D_TIME_THIS_PHASE': (1,),
            'D_TERMINAL': (1,),
            'D_LANE_SUM_WAITING_TIME': (4,),
            'D_VEHICLE_POSITION_IMG': (4, 60),
            'D_VEHICLE_SPEED_IMG': (4, 60),
            'D_VEHICLE_WAITING_TIME_IMG': (4, 60),
            'D_PRESSURE': (1,),
            'D_ADJACENCY_MATRIX': (5,),
            'D_ADJACENCY_MATRIX_LANE': (5,),
            'D_CUR_PHASE_0': (1,),
            'D_LANE_NUM_VEHICLE_0': (4,),
            'D_CUR_PHASE_1': (1,),
            'D_LANE_NUM_VEHICLE_1': (4,),
            'D_CUR_PHASE_2': (1,),
            'D_LANE_NUM_VEHICLE_2': (4,),
            'D_CUR_PHASE_3': (1,),
            'D_LANE_NUM_VEHICLE_3': (4,)
        }, 
        'LIST_STATE_FEATURE': ['cur_phase', 'lane_num_vehicle', 'adjacency_matrix', 'adjacency_matrix_lane'],
        'DIC_REWARD_INFO': {
            'flickering': 0,
            'sum_lane_queue_length': 0,
            'sum_lane_wait_time': 0,
            'sum_lane_num_vehicle_left': 0,
            'sum_duration_vehicle_left': 0,
            'sum_num_vehicle_been_stopped_thres01': 0,
            'sum_num_vehicle_been_stopped_thres1': -0.25,
            'pressure': 0
        },
        'LANE_NUM': {'LEFT': 1, 'RIGHT': 1, 'STRAIGHT': 1},
        'PHASE': {
            'sumo': {
                0: [0, 1, 0, 1, 0, 0, 0, 0],
                1: [0, 0, 0, 0, 0, 1, 0, 1],
                2: [1, 0, 1, 0, 0, 0, 0, 0],
                3: [0, 0, 0, 0, 1, 0, 1, 0]},
            'anon': {
                1: [0, 1, 0, 1, 0, 0, 0, 0],
                2: [0, 0, 0, 0, 0, 1, 0, 1],
                3: [1, 0, 1, 0, 0, 0, 0, 0],
                4: [0, 0, 0, 0, 1, 0, 1, 0]}
        },
        'USE_LANE_ADJACENCY': True,
        'ONE_MODEL': False,
        'NUM_AGENTS': 1, 
        'TOP_K_ADJACENCY': 5,
        'ADJACENCY_BY_CONNECTION_OR_GEO': False,
        'TOP_K_ADJACENCY_LANE': 5,
        'SIMULATOR_TYPE': 'anon', 'BINARY_PHASE_EXPANSION': True,
        'FAST_COMPUTE': True,
        'NEIGHBOR': False,
        'MODEL_NAME': 'CoLight',
        'NUM_ROW': 4,
        'NUM_COL': 4,
        'TRAFFIC_FILE': 'anon_single.json',
        'VOLUME': '300',
        'ROADNET_FILE': 'roadnet_single.json',
        'phase_expansion': {
            1: [0, 1, 0, 1, 0, 0, 0, 0],
            2: [0, 0, 0, 0, 0, 1, 0, 1],
            3: [1, 0, 1, 0, 0, 0, 0, 0],
            4: [0, 0, 0, 0, 1, 0, 1, 0],
            5: [1, 1, 0, 0, 0, 0, 0, 0],
            6: [0, 0, 1, 1, 0, 0, 0, 0],
            7: [0, 0, 0, 0, 0, 0, 1, 1],
            8: [0, 0, 0, 0, 1, 1, 0, 0]},
        'phase_expansion_4_lane': {
            1: [1, 1, 0, 0],
            2: [0, 0, 1, 1]}
    }
    return dic_agent_conf, dic_exp_conf, dic_traffic_env_conf

